### ISSUE TITLE
Miele Dishwasher and further attributes possible

### ISSUE THREAD

**Issue by alehofde** [Grizzelbee/ioBroker.mielecloudservice#187]
Hi Grizzelbee,
great work – happy with the latest version and push data 😊
Now, I have bought a brand-new dishwasher G7915 and this machine was integrated in ioBroker successfully. All is working as expected but I have further requirements 😊
Is there a way to get more data, attributes for the machine?
°Is there an attribute for the AutoDos function. That means the AutoDisk is used for the current washing cycle or not? Need this to count.
°Is there another attribute to get a status of rinse aid?
°Is there another attribute available for salt warning?

Not sure how is the ioBroker.mielecloudservice adapter is operate and if my requirements limited by the machine and the Miele API or is this something what can be added to the ioBroker.mielecloudservice adapter?

Thanks,
alehof

**Comment by Grizzelbee** [comment]
Hi Alehofde,

I`m sorry, but for now I have to deny your requests.  But not because I don't like to implement these things - the Miele-API currently does not provide the requested information. Please take a look at the Miele-Developer homepage for an overview of what information is provided and what not.
**Spoiler alert**: Currently the adapter implements each and every functionalty the API provides - incl. buggy ones (As fas as I know - please drop me a note if not.).

To me

**Comment by alehofde** [comment]
Hello Grizzelbee ,

thank you for the good explanation. I wasn't sure if there is a limit in the Miele API or in the adapter itself. Thanks for the clarification.

Good work and keep it up :-)
