### ISSUE TITLE
No update of EcoFeedback

### ISSUE THREAD

**Issue by benep** [Grizzelbee/ioBroker.mielecloudservice#241]
**Describe the bug**  
Update of `mielecloudservice.0.x.EcoFeedback.currentEnergyConsumption ` and `mielecloudservice.0.x.EcoFeedback.currentWaterConsumption` for my dishwasher does not work anymore. 

**Expected behavior**  
The states should start with 0 and increase while cleaning but stay on the same value since some weeks.

**Versions:**  
 - Adapter version: 6.2.0 but also on some older versions
 - JS-Controller version: 5.7.0
 - Node version: v14.19.2
 - Operating system: RaspberryOS

**Comment by Grizzelbee** [comment]
Please check whether the data points got updated lately by hovering over the value in admin like shown in the following screenshot: 
![grafik](https://user-images.githubusercontent.com/5459426/168474470-248bae2d-eb34-4bbb-af76-6f1be8b31cd2.png)

For my washing mashine and my tumle dryer it works like a charm and since it it the same code I see no reason why it should not work with dish washers. But ... as far as know these values don't start at 0 and increase during the program run. I understood it that way, that the values depend on the selected program and some side conditions - so: if you always run the same program - the values won't change. That's the way I expect it to work - but, to be hones,  since now I haven't cared very much about these values.

**Comment by benep** [comment]
Thank you for your quick reply. 

While writing my initial issue I updated the adapter to 6.2. And now while checking the update datetimes I got new values. I am logging the values on sql and there is a big gap with no data for around 4 weeks. And my scripts did not get triggert. I am not shure I was wrong or an update fixed it. Sorry for the false issue and thank you for your time.

By the way, Do you know if its possible to get the amount of the the remaining dishwascher salt?

And for my dishwasher the values show the real current used amount. This increases while cleaning as shown in my logs:

2022-05-15 15:47:32.825 | info: | javascript.0 (733) | script.js.myscripts.Spülmaschine: | Programmphase: Spülen, Verbrauch: 0.6 kWh & 4 l.
-- | -- | -- | -- | --
2022-05-15 15:55:00.289 | info: | javascript.0 (733) | script.js.myscripts.Spülmaschine: | Programmphase: Klarspülen, Verbrauch: 0.6 kWh & 5 l.
2022-05-15 16:14:20.410 | info: | javascript.0 (733) | script.js.myscripts.Spülmaschine: | Programmphase: Trocknen, Verbrauch: 0.9 kWh & 5 l.
2022-05-15 16:54:25.323 | info: | javascript.0 (733) | script.js.myscripts.Spülmaschine: | Programmphase: Ende, Verbrauch: 0.9 kWh & 8 l.

**Comment by Grizzelbee** [comment]
>  Sorry for the false issue and thank you for your time.

No worries.

> By the way, Do you know if its possible to get the amount of the the remaining dishwascher salt?

Yes - I know, but sadly it's currently not possible. The Miele-API is very generic and therefore many of these information are missing. Even if they are displayed in the Miele App. I'm missing many information for my appiances too and would love to get them. I already told Miele, but got no answer.
