### ISSUE TITLE
Some issues with 6.2.2

### ISSUE THREAD

**Issue by Goersch** [Grizzelbee/ioBroker.mielecloudservice#246]
Hi,

having some issues with 6.2.2
- restarting automatically without I have set up a schedule every minute and thus filling up the log
"instance system.adapter.mielecloudservice.0 scheduled normal terminated and will be restarted on schedule."
- huge warning output "Request made and server responded: ".... 
- filling up the log (with restart of adapter)
"Sorry. No programs to add for device: Waschmaschine ([00014753](tel:00014753)). Reason: No programs have been returned by the API for this device.)"
- same for the dish washer
- this bug was available before, but because the adapter now restarts every minute, it is worse: the coffee machine is switched on on restart of instanz.

Georg

**Comment by Grizzelbee** [comment]
Hi @Goersch 

> restarting automatically without I have set up a schedule every minute and thus filling up the log
> "instance system.adapter.mielecloudservice.0 scheduled normal terminated and will be restarted on schedule."

There is no build-in schedule mechanism. Therefore it must be setup in anywhere your system.

> huge warning output "Request made and server responded: "....
We can argue about whether specific log entries are needed or not or should better be info, warn or debug. From my point of view I like to have log entries if an opereation with the API fails - With my three appliances I have less than 1 entry a day in my log. That the http response is that big ... so what. It's usually one per restart and device and one per failure.

> filling up the log (with restart of adapter)
> "Sorry. No programs to add for device: Waschmaschine (00014753). Reason: No programs have been returned by the API for this device.)"
    same for the dish washer
    this bug was available before, but because the adapter now restarts every minute, it is worse: the coffee machine is switched on on restart of instanz.

Same here. It's one line per device per restart - that it's filling up your Log is because of the scheduled restart - and that's not caused by the adapter.

But anyway: Please provide a debug log of a complete run to see whether there is an issue or not.

**Comment by Goersch** [comment]
well, sorry 😳- the restart was really set up. I missinterpretd the shown schedule. 

I will provide a full debug on the weekend (hard to do on a tablet)

Thanks for the quick support 👍

**Comment by Grizzelbee** [comment]
> well, sorry 😳- the restart was really set up. I missinterpretd the shown schedule.
> Thanks for the quick support 👍
No worries. Your welcome.

>I will provide a full debug on the weekend (hard to do on a tablet)

I can imagine. 😀 
I'm pretty sure that it should have calmed down and most (maybe all) of your issues will be gone then.
Btw: If not already done: Please disable the restart scheduling completely - it shouldn't be neccesary anymore since it has only been a workaround for the silent crashes of the adapter which won't happen anymore.

**Comment by Grizzelbee** [comment]
Addintion after retest:
>filling up the log (with restart of adapter)
>"Sorry. No programs to add for device: Waschmaschine (00014753). Reason: No programs have been returned by the API for this >device.)"

This happens for my washing machine and my dryer too - but not for my coffee machine.
And it happens on the miele homepage as well. Therefore it's no systematic failure of the adapter, but a (hopefully temporary) issue of the API. I think it's an temporary issue since during my tests from time to time the API reponded with programs for these devices already.
But ... since there is no list which appliances currently support `/programs`  I simply need to test all - and some respond with this failure.
I'll make my mind whether I filter these warnings and drop them only as debug logs.

**Comment by Goersch** [comment]
We can close this issue - issues were caused due to my wrong set up of the scheduler.
