### ISSUE TITLE
Feature request: Energy consumption 

### ISSUE THREAD

**Issue by MrIngenieur** [Grizzelbee/ioBroker.mielecloudservice#338]
Hi, 

in the Miele iOS app you can see energy consumption in kWh of washing machines or dryer, depending on the actual program running, 30°C, 60°C and so on.

Would be great to have that also in the iobroker adapter.

**Comment by Grizzelbee** [comment]
Thank you for your Feature request - and I am afraid and happy at the same time to say: 
This feature is already implemented - since approx. 2 years and it works like a charm for at least 
Washing machines:
![grafik](https://user-images.githubusercontent.com/5459426/211291247-f1a0a3a0-6749-4092-bd71-30d428bf4bbe.png)

Tumble dryers:
![grafik](https://user-images.githubusercontent.com/5459426/211291602-c4ab5f23-7cc6-4458-921e-df4351278a01.png)

Dish washers:
![grafik](https://user-images.githubusercontent.com/5459426/211291934-b2bac286-7c75-44b8-b35a-93a3c46d0fab.png)


As you may see - some appliance classes are supported - some not (mostly these where it makes no sense live coffee machines, hoods, ...). And in addition to that - not all modells in an appliance class report these information. Means: Some washing machines report these information, some not. Miele decides which one do and which one not. And to make this all more complicated as it's already is: Not all information which is provided in the App is also currently provided on the API this adapter uses. But good news: Miele is working on it to improve the API.

Conclusion:
If you have this EcoFeedback folder - you're a lucky guy and you'll find the desired information there.
If not - bad luck. The only thing you can do is to wait for a future version of the API and send a little prayer.
I'm sorry for not having more promising things to say.

**Comment by Grizzelbee** [comment]
closed due to no further response.
