### ISSUE TITLE
Api Polling time in seconds

### ISSUE THREAD

**Issue by koburg** [Grizzelbee/ioBroker.mielecloudservice#54]
Could it be possible to setup API polling time to seconds instead of minutes ?

**Comment by Grizzelbee** [comment]
Of course it could be possible. It's only a minor change. But I wonder why? What is the use case that requires polling in less than 1 minute?

**Comment by koburg** [comment]
Because the Update is to Slow when using Washing  machine. I want updates more frequently .

**Comment by Grizzelbee** [comment]
Yeah. That's what I already got from the question.
But: I dont understand the benefit of getting the message that the washing machine has finished or did whatever with a delay of 1 second instead of 1 minute after having run for three hours.

Please don't get me wrong: I'm not against changing it to seconds - I only like to understand your benefit - since it affects all current users.

**Comment by koburg** [comment]
Just make it possible to choose sec or min. I have seen other adapters got this option. I just want fast notifications so I can do something like turn on off the washing machine etc. I program plc daily and use ms but sec would be nice enough option.
